name: CI setup for Go #Name the workflow
on: # on event keyword
  push: 
    branches: [main] #identifying branch
    

jobs: #job to execute on event
  my-job: # can be any identifier, jobs1, build1 etc
    name: My Job
    runs-on: ubuntu-latest # specify os in virtual machine
    steps:
    - name: Print a greeting
      run: |
        ls
        echo Hello there! #run terminal command
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.3
      with:
        # The Go version to download (if necessary) and use. Supports semver spec and ranges.
        go-version: 1.16.5 # optional
    - name: show Go version
      run: go version #verify Go is installed and show Go version
