name: CI setup for Go #Name the workflow
on: # on event keyword
  push: 
    branches: [main] #identifying branch
    

jobs: #job to execute on event
  my-job: # can be any identifier, jobs1, build1 etc
    name: My Job
    runs-on: ubuntu-latest # specify os in virtual machine
    steps:
    - name: Print a greeting
      run: |
        ls
        echo Hello there! #run terminal command
        
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.3
      with:
        # The Go version to download (if necessary) and use. Supports semver spec and ranges.
        go-version: 1.16.5 # optional
    - name: show Go version
      run: go version #verify Go is installed and show Go version
      
    - name: Checkout our codes #bring repo code to virtual environment
      uses: actions/checkout@v2
      
    - name: Check file system #check virtual environment has my files
      run: |
        ls
        cat calc.go #print the contents of calc.go
        cat calc_goblin_test.go 

    - name: Checkout private repo remotely
      uses: actions/checkout@v2
      with:
        repository: lowkh2/GoSchoolRemoteExample #hidden repo i am trying to access
        path: virtualRepoFolder #folder to save to in my virtual env
        token: ${{secrets.GO_SECRET}} #the secret in my settings
        
    - name: Show hidden files
      run: |
        cd virtualRepoFolder #access folder of interest in virutal env
        ls
        cat myText.txt #show content of file
        cd ..
        
    - name: Install dependencies for GO and test calc
      run: |
        go get github.com/franela/goblin #go packages
        go get github.com/tebeka/go2xunit
        go mod init calc.go
        go mod tidy
        go test -v 
